### ISSUE TITLE
Investigate why memcached spends a lot of time in tcp_sendmsg

### ISSUE THREAD

**Issue by racktear** [tarantool/memcached#28]
Example:

https://gist.githack.com/anonymous/fed0b49cd8a3544cd91f7cff543ff1b7/raw/391ceb49bafb0f3904416d363fa6da15ef473b2d/g.svg

**Comment by bigbes** [comment]
I've pushed some fixes to memcached on the previous week -
https://github.com/tarantool/memcached/commit/d5843d6ed3e8f3ea476189ead3c90724d3206a08
You've checked with this patch?

With best regards, Eugene.

2016-09-26 11:58 GMT+03:00 Konstantin Nazarov <notifications@github.com>:

**Comment by racktear** [comment]
Yes. Still reproduces.

https://gist.githack.com/anonymous/ad27d934381ef80de88e33bcfee11e84/raw/f4ab4782a0032dfa23508ed99e2d0d28b4b85b0f/g.svg
